### PR TITLE
 Highlight the same versions with the same colors

### LINKED ISSUE #3: Each version should have the same color
Hey! Thanks for the awesome tool! 👍

I want to propose an enhancement. What if each version will have the same color?

For example, my project has 2 versions of `@babel/core` `7.0.0` and one `6.0.0`. It will be easier to determine exact versions with a cursory glance.

### PR DESCRIPTION
**Pull request by SleepWalker**
Hello, @ranyitz 

this PR closes #3

this is how it will look like:

image

This behavior can be disabled using `--disable-colors` key, which will render the output as it was before version highlighting implemented.

### CODE REVIEW

**Comment by SleepWalker** [comment]
> sorry for the bikeshedding bike

Oh that's okay. It's really good, that you've polished the colors :+1:

**Comment by SleepWalker** [comment]
@ranyitz done

**Comment by ranyitz** [comment]
Thanks @SleepWalker! awesome work 🎉

**Comment by ranyitz** [comment]
Your feature was release on [version 0.11.0](https://github.com/ranyitz/qnm/blob/master/CHANGELOG.md#0110-may-26-2018)

**Pull request merged**
